apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-2
  name: api-2-deployment
spec:
  replicas: 0
  selector:
    matchLabels:
      app: api-2
  template:
    metadata:
      labels:
        app: api-2
    spec:
      containers:
      - name: api-2-containter
        image: tutum/hello-world
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: config-map-api-2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-2
  name: api-2-service
spec:
  type: NodePort
  ports:
  - name: webport
    port: 80
    targetPort: 80
  selector:
    app: api-2    